"""Add calendar integration fields

Revision ID: 0c1d74f16b27
Revises: d928d619110d
Create Date: 2025-10-28 09:38:47.265702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1d74f16b27'
down_revision: Union[str, None] = 'd928d619110d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('calendar_provider', sa.String(), nullable=True))
    op.add_column('bets', sa.Column('calendar_event_id', sa.String(), nullable=True))
    op.add_column('bets', sa.Column('calendar_created_at', sa.DateTime(), nullable=True))
    op.add_column('bets', sa.Column('calendar_timezone', sa.String(), nullable=True))
    op.add_column('bets', sa.Column('calendar_reminder_min', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('preferred_calendar_provider', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('timezone', sa.String(), nullable=False, server_default='America/New_York'))
    op.add_column('user_settings', sa.Column('calendar_reminder_min', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('user_settings', sa.Column('google_oauth_connected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_settings', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'google_refresh_token')
    op.drop_column('user_settings', 'google_oauth_connected')
    op.drop_column('user_settings', 'calendar_reminder_min')
    op.drop_column('user_settings', 'timezone')
    op.drop_column('user_settings', 'preferred_calendar_provider')
    op.drop_column('bets', 'calendar_reminder_min')
    op.drop_column('bets', 'calendar_timezone')
    op.drop_column('bets', 'calendar_created_at')
    op.drop_column('bets', 'calendar_event_id')
    op.drop_column('bets', 'calendar_provider')
    # ### end Alembic commands ###
