"""Initial migration

Revision ID: fa58827a159a
Revises: 
Create Date: 2025-10-26 23:17:15.673389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa58827a159a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sportsbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bet_name', sa.String(), nullable=False),
    sa.Column('sport', sa.Enum('NFL', 'NBA', 'MLB', 'NHL', 'NCAAF', 'NCAAB', 'SOCCER', 'MMA', 'OTHER', name='sport'), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('market_type', sa.Enum('ML', 'SPREAD', 'TOTAL', 'PROP', 'PARLAY', 'FUTURE', 'OTHER', name='markettype'), nullable=False),
    sa.Column('team_or_player', sa.String(), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', 'VOID', 'CASHOUT', name='betstatus'), nullable=False),
    sa.Column('result_profit', sa.Float(), nullable=True),
    sa.Column('cashout_amount', sa.Float(), nullable=True),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('closing_odds_american', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parlay_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['sportsbooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_unit', sa.Float(), nullable=False),
    sa.Column('default_book_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_book_id'], ['sportsbooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('bets')
    op.drop_table('sportsbooks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
